trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    versionSpec: '3.8'
  displayName: 'Install Python 3.8'
- script: pip install checkov
  displayName: 'Install Checkov'
- script: checkov -d . --bc-api-key 44147500-b4b8-481a-9858-73b014f6f131::3yONy+GqKzZiGPYBFloa32WN5sw= --repo-id nathan-aw/pipelines-java --branch main
  displayName: 'Scan with Prisma Cloud'
  env:
    PRISMA_API_URL: https://api.anz.prismacloud.io