trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    versionSpec: '3.7'
  displayName: 'Install Python 3.7'
- script: pip uninstall urllib3
  displayName: 'pip uninstall urllib3'
- script: pip install requests
  displayName: 'Install request'
- script: pip install checkov
  displayName: 'Install Checkov'
- script: checkov -d . --bc-api-key 9bfab0b2-bd8d-41b5-91a3-13989a97ff6a::pgbj5rlUvU7Jl0R7nnucHc8ETh8= --repo-id nathan-aw/pipelines-java --branch main
  displayName: 'Scan with Prisma Cloud'
  env:
    PRISMA_API_URL: https://api.anz.prismacloud.io
