version: 0.2
env:
  variables:
      BC_SOURCE: "codebuild"
      PRISMA_API_URL: "https://api.sg.prismacloud.io"
  parameter-store:
      BC_API_KEY: "bc-api-key"
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
       - pip3 install bridgecrew
       - echo Installing codebuild-extras...
       - curl -fsSL https://raw.githubusercontent.com/bridgecrewio/aws-codebuild-extras/master/install >> extras.sh
       - . ./extras.sh
  build:
    commands:
       - bridgecrew -d . --bc-api-key $BC_API_KEY --repo-id 759842748619/code-security --branch master -s
